apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grayround
  name: grayround
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grayround
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grayround
    spec:
      containers:
      - image: docker.io/dbgurum/grayround:v1.0
        name: grayround
        ports:
        - containerPort: 80
