apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grayround
  name: grayround-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: grayround
  type: LoadBalancer
status:
  loadBalancer: {}
